[project]
name = 'Tokenized-Sustainable-Fishery-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.catch-reporting]
path = 'contracts/catch-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.market-access]
path = 'contracts/market-access.clar'
clarity_version = 2
epoch = 2.5

[contracts.quota-allocation]
path = 'contracts/quota-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.vessel-registration]
path = 'contracts/vessel-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
